version: '3.10'

networks:
  mynetwork:
    driver: bridge

services:
  redis_server:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - mynetwork

  mypostgres:
    image: postgres
    container_name: mypostgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    restart: always
    networks:
      - mynetwork
